---

- name: Install required packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present

- name: Create nfs server directory
  file:
    path: /srv/ganeti/shared-file-storage
    state: directory

- name: Export shared-file-storage folder
  lineinfile:
    path: /etc/exports
    regexp: "^/srv/ganeti/shared-file-storage\\s"
    line: "/srv/ganeti/shared-file-storage  192.168.1.0/24(rw,sync,no_wdelay,no_subtree_check,no_root_squash)"

- name: Restart NFS server
  service:
    name: nfs-kernel-server
    enabled: yes
    state: restarted

- name: Reload NFS exports
  command: exportfs -ra


