---

- hosts: ganeti_nodes
  user: root
  gather_facts: False
  tasks:
    - name: Wait for SSH
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

- hosts: 192.168.122.11
  user: root
  roles:
    - nfs_server

- hosts: ganeti_nodes:!192.168.122.11
  user: root
  roles:
    - nfs_client

- hosts: ganeti_nodes
  user: root
  roles:
    - storage
    - bridge_networking
    - drbd
    - ganeti

- hosts: 192.168.122.11
  user: root
  tasks:
    - name: Initialise cluster
      command: gnt-cluster init --vg-name gnt --master-netdev eth0 --master-netmask 24 --enabled-hypervisors kvm --nic-parameters mode=bridged,link=virt-bridge --enabled-disk-templates=plain,file,drbd,sharedfile --shared-file-storage-dir=/srv/ganeti/shared-file-storage --file-storage-dir=/srv/ganeti/file-storage --default-iallocator hail --hypervisor-parameters kvm:spice_bind=0.0.0.0,spice_use_tls=true,kernel_path= --ipolicy-bounds-specs min:nic-count=0,cpu-count=1,disk-count=0,spindle-use=0,disk-size=512M,memory-size=128M/max:nic-count=8,cpu-count=48,disk-count=8,spindle-use=8,disk-size=1TB,memory-size=1TB --ipolicy-disk-templates=plain,file,drbd,sharedfile staging-cluster.ganeti.org
    - name: Add node
      command: gnt-node add --no-ssh-key-check gnt-test02
    - name: Add node
      command: gnt-node add --no-ssh-key-check gnt-test03
