---
- name: Configure network bridge
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"
  notify: Start network bridge

- name: Remove all configured nameservers from resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    state: absent

- name: Use the local libvirt-provided nameserver (for instance name resolution)
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: "nameserver {{ net_nameserver }}"
