---
- name: Install required packages
  apt:
    name:
      - ganeti-instance-debootstrap
      - ganeti-os-noop

- name: Make sure cluster name is present in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ganeti_cluster_ip }}   staging-cluster.ganeti.org"

- name: Install ganeti rapi users file (1/2)
  file:
    path: /var/lib/ganeti/rapi
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install ganeti rapi users file (2/2)
  copy:
    dest: /var/lib/ganeti/rapi/users
    content: "ganeti-qa ganeti-qa write"
    owner: root
    group: root
    mode: "0644"

- name: Create file storage path
  file:
    path: /srv/ganeti/file-storage
    state: directory

- name: Whitelist shared-file storage path in /etc/ganeti/file-storage-paths
  copy:
    src: file-storage-paths
    dest: /etc/ganeti/file-storage-paths
    owner: root
    group: root
    mode: "0644"

- name: Install statically linked busybox version for custom initrd
  apt:
    name: busybox-static
    state: present

- name: Copy script to create busybox initrd
  copy:
    src: create_busybox_initrd.sh
    dest: /usr/local/sbin/create_busybox_initrd.sh
    owner: root
    group: root
    mode: "0750"

- name: Create busybox initrd for use in ganeti instances
  command: /usr/local/sbin/create_busybox_initrd.sh

- name: Create VNC password file
  copy:
    dest: /etc/ganeti/vnc-cluster-password
    owner: root
    group: root
    mode: "0644"
    content: "very-secure-vnc-password"

- name: Install ganeti defaults (enable debug logging for all services)
  copy:
    src: ganeti.defaults
    dest: /etc/default/ganeti
    owner: root
    group: root
    mode: "0644"

- name: "QUICKFIX: disable SSH strict host key checking in ganeti-testsuite"
  command: "sed -i -e 's/strict=True/strict=False/' /usr/src/ganeti/qa/qa_utils.py"

- name: "QUICKFIX: Install colors.py (missing from Ganeti source)"
  copy:
    src: colors.py
    dest: /usr/src/ganeti/qa/colors.py
    owner: root
    group: root
    mode: "0644"

- name: "QUICKFIX: install these packages to make the kvm-ifup-os script pass the tests in ganeti-testsuite"
  apt:
    name:
      - net-tools
      - ethtool
      - dnsmasq

- name: Install cronjob to overwrite /var/log/ganeti/qa-output.log
  copy:
    dest: /etc/cron.d/cleanup-ganeti-qa-log
    owner: root
    group: root
    mode: "0644"
    content: "*/5 * * * * root if [ -f /var/log/ganeti/qa-output.log ]; then echo > /var/log/ganeti/qa-output.log; fi\n"

